# Generated by Django 3.0.3 on 2020-02-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=30)),
                ('author', models.CharField(default='', max_length=30)),
                ('description', models.TextField(default='', max_length=60)),
                ('image', models.ImageField(upload_to='images')),
                ('category', models.CharField(choices=[('Adventure', 'Adventure'), ('Fantasy', 'Fantasy'), ('Mystery', 'Mystery'), ('SciFi', 'SciFi')], default='Adventure', max_length=9)),
                ('text', models.TextField(default='', max_length=600)),
                ('published', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
