# Generated by Django 3.0.3 on 2020-02-29 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('story', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='image',
        ),
        migrations.AlterField(
            model_name='story',
            name='text',
            field=models.TextField(default='', max_length=3000),
        ),
    ]
